###############################################################
## Packages / Groups / Alarm
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alarm'

    ################################################
    ## Group
    ################################################

    ################################################
    ## Sensor Fire
    ################################################

    ################################################
    ## Sensor Water
    ################################################


################################################
## Alarm
################################################

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

################################################
## Automation
################################################

automation:
  - alias: 'Trigger alarm while armed away'
    trigger:
      - platform: state
        entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm

  - alias: 'Send notification when alarm triggered'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'triggered'
    action:
      - service: notify.telegram_house
        data_template:
          message: >-
            "\u2618 Hemlarm har triggat."
