###############################################################
## Packages / Groups / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

    ################################################
    ## Group
    ################################################

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"
      icon: mdi:battery

    ################################################
    ## Sensor
    ################################################

    sensor.tradfri_remote_control:
      <<: *customize
      friendly_name: "Trådfri controll Bedroom"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_remote_control_2:
      <<: *customize
      friendly_name: "Trådfri controll Living Room"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_remote_control_3:
      <<: *customize
      friendly_name: "Trådfri controll Babys Room"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_motion_sensor:
      <<: *customize
      friendly_name: "Motion Sensor Walk-in Closet"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_motion_sensor_2:
      <<: *customize
      friendly_name: "Motion Sensor Laundry Room"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_motion_sensor_3:
      <<: *customize
      friendly_name: "Motion Sensor Entry"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_motion_sensor_4:
      <<: *customize
      friendly_name: "Motion Sensor Storage Boxes"
      hidden: false
      icon: mdi:battery

    sensor.tradfri_motion_sensor_5:
      <<: *customize
      friendly_name: "Motion Sensor Storage Tools"
      hidden: false
      icon: mdi:battery

    sensor.fibaro_system_fgms001_motion_sensor_battery:
      <<: *customize
      friendly_name: "Motion Sensor Entry Bathroom"
      hidden: false
      icon: mdi:battery

    sensor.plantmonitor1_battery:
      <<: *customize
      friendly_name: "Spathiphyllum Kochii"
      hidden: false
      icon: mdi:battery

    sensor.plantmonitor2_battery:
      <<: *customize
      friendly_name: "Spathiphyllum Gold Cupid"
      hidden: false
      icon: mdi:battery

    sensor.plantmonitor3_battery:
      <<: *customize
      friendly_name: "Capsicum Bomba red"
      hidden: false
      icon: mdi:battery

    sensor.plantmonitor4_battery:
      <<: *customize
      friendly_name: "Cherry Tomato"
      hidden: false
      icon: mdi:battery

################################################
## Graph
################################################

history_graph:
  batteries:
    name: 'Batteries Graph'
    entities:
      - sensor.tradfri_remote_control
      - sensor.tradfri_remote_control_2
      - sensor.tradfri_remote_control_3
      - sensor.tradfri_motion_sensor
      - sensor.tradfri_motion_sensor_2
      - sensor.tradfri_motion_sensor_3
      - sensor.tradfri_motion_sensor_4
      - sensor.tradfri_motion_sensor_5
      - sensor.fibaro_system_fgms001_motion_sensor_battery
      - sensor.bathroom_upstairs_temperature_battery
      - sensor.master_bedroom_temperature_battery
      - sensor.plantmonitor1_battery
      - sensor.plantmonitor2_battery
      - sensor.plantmonitor3_battery
      - sensor.plantmonitor4_battery
      - sensor.spathiphyllum_kochii_battery
      - sensor.spathiphyllum_gold_cupid_battery
      - sensor.capsicum_bomba_red_battery
      - sensor.cherry_tomato_battery
      - sensor.danfoss_z_thermostat_014g0013_battery
      - sensor.danfoss_z_thermostat_014g0013_battery_2
      - sensor.danfoss_z_thermostat_014g0013_battery_3
      - sensor.xiaomi_vacuum_cleaner_battery
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  batteries:
    control: hidden
    entities:
      - sensor.tradfri_remote_control
      - sensor.tradfri_remote_control_2
      - sensor.tradfri_remote_control_3
      - sensor.tradfri_motion_sensor
      - sensor.tradfri_motion_sensor_2
      - sensor.tradfri_motion_sensor_3
      - sensor.tradfri_motion_sensor_4
      - sensor.tradfri_motion_sensor_5
      - sensor.fibaro_system_fgms001_motion_sensor_battery
      - sensor.plantmonitor1_battery
      - sensor.plantmonitor2_battery
      - sensor.plantmonitor3_battery
      - sensor.plantmonitor4_battery
      - sensor.spathiphyllum_kochii_battery
      - sensor.spathiphyllum_gold_cupid_battery
      - sensor.capsicum_bomba_red_battery
      - sensor.cherry_tomato_battery
      - sensor.danfoss_z_thermostat_014g0013_battery
      - sensor.danfoss_z_thermostat_014g0013_battery_2
      - sensor.danfoss_z_thermostat_014g0013_battery_3
      - sensor.xiaomi_vacuum_cleaner_battery
      - history_graph.batteries_graph
