###############################################################
## Packages / Groups / Humidity
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'humidity'

    ################################################
    ## Group
    ################################################

    group.humidity:
      <<: *customize
      friendly_name: "Humidity"
      icon: mdi:thermometer

    ################################################
    ## Sensor
    ################################################

################################################
## Graph
################################################

history_graph:
  humidity:
    name: 'Humidity Graph'
    entities:
      - sensor.entry_humidity
      - sensor.climate_bathroom_upstairs_humidity
      - sensor.climate_master_bedroom_humidity
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  humidity:
    control: hidden
    entities:
      - sensor.entry_humidity
      - sensor.climate_bathroom_upstairs_humidity
      - sensor.climate_master_bedroom_humidity
      - history_graph.humidity_graph
