###############################################################
## Packages / Groups / Light Sensors
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light_sensors'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        hidden: false

    ################################################
    ## Group
    ################################################

    group.light_sensors:
      <<: *customize
      friendly_name: "Light Sensor"
      icon: mdi:run

    ################################################
    ## Sensor
    ################################################

    sensor.plantmonitor1_light_intensity:
      <<: *customize
      friendly_name: "Luminance Spathiphyllum Kochii"

    sensor.plantmonitor2_light_intensity:
      <<: *customize
      friendly_name: "Luminance Spathiphyllum Gold Cupid"

################################################
## Group
################################################

group:
  light_sensors:
    control: hidden
    entities:
      - sensor.plantmonitor1_light_intensity
      - sensor.plantmonitor2_light_intensity
      - sensor.fibaro_system_fgms001_motion_sensor_luminance
