###############################################################
## Packages / Groups / Light Sensors
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light_sensors'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        hidden: false

    ################################################
    ## Group
    ################################################

    group.light_sensors:
      <<: *customize
      friendly_name: "Light Sensor"
      icon: mdi:run

    ################################################
    ## Sensor
    ################################################

    sensor.plantmonitor1_light_intensity:
      <<: *customize
      friendly_name: "Spathiphyllum Kochii"

    sensor.plantmonitor2_light_intensity:
      <<: *customize
      friendly_name: "Spathiphyllum Gold Cupid"

    sensor.plantmonitor3_light_intensity:
      <<: *customize
      friendly_name: "Capsicum Bomba red"

    sensor.plantmonitor4_light_intensity:
      <<: *customize
      friendly_name: "Cherry Tomato"

################################################
## Graph
################################################

history_graph:
  lux:
    name: 'Lux Graph'
    entities:
      - sensor.plantmonitor1_light_intensity
      - sensor.plantmonitor2_light_intensity
      - sensor.plantmonitor3_light_intensity
      - sensor.plantmonitor4_light_intensity
      - sensor.fibaro_system_fgms001_motion_sensor_luminance
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  light_sensors:
    control: hidden
    entities:
      - sensor.plantmonitor1_light_intensity
      - sensor.plantmonitor2_light_intensity
      - sensor.plantmonitor3_light_intensity
      - sensor.plantmonitor4_light_intensity
      - sensor.fibaro_system_fgms001_motion_sensor_luminance
      - history_graph.lux_graph
