###############################################################
## Packages / Groups / Motion
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.motion:
      <<: *customize
      friendly_name: "Motion"
      icon: mdi:run

    ################################################
    ## Sensor
    ################################################

    sensor.fibaro_system_fgms001_motion_sensor_general:
      <<: *customize
      friendly_name: "Bathroom"
      hidden: false
      icon: mdi:run

################################################
## Group
################################################

group:
  motion:
    control: hidden
    entities:
      - sensor.fibaro_system_fgms001_motion_sensor_general
