###############################################################
## Packages / Groups / Motion
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion'

    ################################################
    ## Group
    ################################################

    group.motion:
      <<: *customize
      friendly_name: "Motion"
      icon: mdi:run

    ################################################
    ## Sensor
    ################################################

    binary_sensor.fibaro_system_fgms001_motion_sensor:
      <<: *customize
      friendly_name: "Bathroom"
      hidden: false
      icon: mdi:run
################################################
## Graph
################################################

history_graph:
  motion:
    name: 'Motion Graph'
    entities:
      - binary_sensor.fibaro_system_fgms001_motion_sensor
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  motion:
    control: hidden
    entities:
      - binary_sensor.fibaro_system_fgms001_motion_sensor
      - history_graph.motion_graph
