################################################################
## Packages / Groups / People
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/people'

    ################################################
    ## Device Tracker
    ################################################

    ################################################
    ## Group
    ################################################

    group.person_landrash:
      <<: *customize
      friendly_name: "Landrash"
      icon: mdi:human-male

    group.person_jojo:
      <<: *customize
      friendly_name: "Jojo"
      icon: mdi:human-female

################################################
## Group
################################################

  person_landrash:
    control: hidden
    entities:
      - device_tracker.landrash

  person_jojo:
    control: hidden
    entities:
      - device_tracker.jojo
