###############################################################
## Packages / Groups / Power Management
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'power_management'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.power_monitors:
      <<: *customize
      friendly_name: "Power Monitors"
      icon: mdi:run

    ################################################
    ## Sensor
    ################################################


################################################
## Group
################################################

group:
  power_monitors:
    control: hidden
    entities:
      - sensor.fibaro_system_fgwpef_wall_plug_power_2
      - sensor.fibaro_system_fgwpef_wall_plug_energy_2
      - sensor.fibaro_system_fgd212_dimmer_2_power
      - sensor.fibaro_system_fgd212_dimmer_2_energy
