################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    group.bathroom_entry:
      <<: *customize
      friendly_name: "Bathroom Entry"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    group.hallway:
      <<: *customize
      friendly_name: "Hallway"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.walkin_closet:
      <<: *customize
      friendly_name: "Walk-in Closet"

    group.second_bedroom:
      <<: *customize
      friendly_name: "Babys Room"

    group.geek_room:
      <<: *customize
      friendly_name: "Geek Room"

################################################
## Group
################################################

group:
  bathroom_entry:
    control: hidden
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2

  back_porch:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_6

  entry:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_5

  front_porch:
    control: hidden
    entities:
      - light.front_porch

  hallway:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_3

  kitchen:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_7
      - light.tradfri_bulb_e27_ws_opal_980lm_8
      - light.tradfri_bulb_e27_ws_opal_980lm_9

  laundry_room:
    control: hidden
    entities:
      - light.floalt_panel_ws_60x60
      - switch.fibaro_system_fgwpef_wall_plug_switch_2

  living_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_3
      - light.tradfri_bulb_e27_w_opal_1000lm_4
      - light.floor_light
      - media_player.living_room_tv
      - media_player.kodi_master_bedroom_host

  master_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_ws_opal_400lm
      - light.tradfri_bulb_e14_ws_opal_400lm_2
      - switch.table_fan
      - light.rgb_christmas_tree
      - scene.good_night
      - media_player.master_bedroom_tv

  walkin_closet:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_w_opal_1000lm

  second_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_6
      - light.blue_balls

  geek_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_2
      - light.tradfri_bulb_e27_cws_opal_600lm
      - light.living_room_sensornode_light
