################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    group.hallway:
      <<: *customize
      friendly_name: "Hallway"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.walkin_closet:
      <<: *customize
      friendly_name: "Walk-in Closet"

    group.geek_room:
      <<: *customize
      friendly_name: "Geek Room"

################################################
## Group
################################################

group:
  back_porch:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_6
      - switch.433_mhz_outlet_1
      - switch.433_mhz_outlet_2
      - switch.433_mhz_outlet_3

  entry:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_4

  front_porch:
    control: hidden
    entities:
      - light.front_porch

  hallway:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_3

  kitchen:
    control: hidden
    entities:
      - light.kitchen

  laundry_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_5
      - switch.fibaro_system_fgwpef_wall_plug_switch
      - sensor.fibaro_system_fgwpef_wall_plug_power

  living_room:
    control: hidden
    entities:
      - light.unnamed_device
      - light.tradfri_bulb_e14_w_opch_400lm_3
      - media_player.living_room_tv
      - sensor.openmqttgateway2_temperature
      - sensor.openmqttgateway2_humidity

  master_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_ws_opal_400lm
      - light.tradfri_bulb_e14_ws_opal_400lm_2
      - media_player.master_bedroom_tv

  walkin_closet:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_w_opal_1000lm

  geek_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_2
      - sensor.openmqttgateway1_temperature
      - sensor.openmqttgateway1_humidity
