################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    group.bathroom_entry:
      <<: *customize
      friendly_name: "Bathroom Entry"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    group.hallway:
      <<: *customize
      friendly_name: "Hallway"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.walkin_closet:
      <<: *customize
      friendly_name: "Walk-in Closet"

    group.second_bedroom:
      <<: *customize
      friendly_name: "Babys Room"

    group.office:
      <<: *customize
      friendly_name: "Geek Room"

################################################
## Group
################################################

group:
  bathroom_entry:
    control: hidden
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2

  back_porch:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_6_2
      - switch.tradfri_control_outlet

  entry:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_5

  front_porch:
    control: hidden
    entities:
      - light.christmas_lights_front

  hallway:
    control: hidden
    entities:
      - light.light_stairs_celling

  kitchen:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_2_2
      - light.tradfri_bulb_e14_w_opch_400lm_3_2
      - media_player.koks_hogtalare

  laundry_room:
    control: hidden
    entities:
      - light.floalt_panel_ws_60x60

  living_room:
    control: hidden
    entities:
      - light.light_livingroom_diningtable
      - light.tradfri_bulb_e14_ws_opal_400lm_7
      - media_player.living_room_tv

  master_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_ws_opal_400lm
      - light.tradfri_bulb_e14_ws_opal_400lm_2
      - light.rgb_christmas_tree
      - scene.good_night
      - media_player.master_bedroom_tv
      - media_player.kodi_master_bedroom_host

  walkin_closet:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_w_opal_1000lm

  second_bedroom:
    control: hidden
    entities:
      - light.light_second_bedroom_celling
      - light.christmas_star

  office:
    control: hidden
    entities:
      - light.light_office_celling
      - media_player.kontor
