################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.back_porch:
      <<: *customize
      friendly_name: "Back Porch"

    group.entry:
      <<: *customize
      friendly_name: "Entry"

    group.front_porch:
      <<: *customize
      friendly_name: "Front Porch"

    group.hallway:
      <<: *customize
      friendly_name: "Hallway"

    group.kitchen:
      <<: *customize
      friendly_name: "Kitchen"

    group.laundry_room:
      <<: *customize
      friendly_name: "Laundry Room"

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"

    group.walkin_closet:
      <<: *customize
      friendly_name: "Walk-in Closet"

    group.second_bedroom:
      <<: *customize
      friendly_name: "Babys Room"

    group.geek_room:
      <<: *customize
      friendly_name: "Geek Room"

################################################
## Group
################################################

group:
  back_porch:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_6
      - switch.433_mhz_outlet_1

  entry:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_5

  front_porch:
    control: hidden
    entities:
      - light.front_porch

  hallway:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_3

  kitchen:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_opal_980lm_7
      - light.tradfri_bulb_e27_w_opal_1000lm_4
      - light.tradfri_bulb_e27_cws_opal_600lm
      - climate.danfoss_z_thermostat_014g0013_heating_1

  laundry_room:
    control: hidden
    entities:
      - light.floalt_panel_ws_60x60
      - switch.fibaro_system_fgwpef_wall_plug_switch_2
      - sensor.fibaro_system_fgwpef_wall_plug_energy_2

  living_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_3
      - switch.433_mhz_outlet_3
      - media_player.living_room_tv
      - sensor.openmqttgateway2_temperature
      - sensor.openmqttgateway2_humidity
      - vacuum.xiaomi_vacuum_cleaner
      - climate.danfoss_z_thermostat_014g0013_heating_1_2

  master_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_ws_opal_400lm
      - light.tradfri_bulb_e14_ws_opal_400lm_2
      - media_player.master_bedroom_tv
      - switch.433_mhz_outlet_2
      - scene.good_night


  walkin_closet:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_w_opal_1000lm

  second_bedroom:
    control: hidden
    entities:
      - light.tradfri_bulb_e27_ws_clear_950lm_6

  geek_room:
    control: hidden
    entities:
      - light.tradfri_bulb_e14_w_opch_400lm_2
      - sensor.openmqttgateway1_temperature
      - sensor.openmqttgateway1_humidity
