###############################################################
## Packages / Groups / temperature
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'temperature'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer
    group.thermostat:
      <<: *customize
      friendly_name: "Thermostat"
      icon: mdi:thermostat

    ################################################
    ## Sensor
    ################################################

    ################################################
    ## Thermostat
    ################################################

    climate.danfoss_z_thermostat_014g0013_heating_1:
      <<: *customize
      friendly_name: "Thermostat Kitchen"
      hidden: false

    climate.danfoss_z_thermostat_014g0013_heating_1_2:
      <<: *customize
      friendly_name: "Thermostat Living Room Small Window"
      hidden: false

    climate.danfoss_z_thermostat_014g0013_heating_1_3:
      <<: *customize
      friendly_name: "Thermostat Living Room Large Window"
      hidden: false

################################################
## Graph
################################################

history_graph:
  temperature:
    name: 'Temperature Graph'
    entities:
      - sensor.living_room_temperature
      - sensor.geek_room_temperature
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.plantmonitor1_temperature
      - sensor.plantmonitor2_temperature
      - sensor.plantmonitor3_temperature
      - sensor.plantmonitor4_temperature
    hours_to_show: 24
    refresh: 60
  thermostat:
    name: 'Thermostat Graph'
    entities:
      - climate.danfoss_z_thermostat_014g0013_heating_1
      - climate.danfoss_z_thermostat_014g0013_heating_1_2
      - climate.danfoss_z_thermostat_014g0013_heating_1_3
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  temperature:
    control: hidden
    entities:
      - sensor.living_room_temperature
      - sensor.geek_room_temperature
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.plantmonitor1_temperature
      - sensor.plantmonitor2_temperature
      - sensor.plantmonitor3_temperature
      - sensor.plantmonitor4_temperature
      - history_graph.temperature_graph
  thermostat:
    control: hidden
    entities:
      - climate.danfoss_z_thermostat_014g0013_heating_1
      - climate.danfoss_z_thermostat_014g0013_heating_1_2
      - climate.danfoss_z_thermostat_014g0013_heating_1_3
      - history_graph.thermostat_graph
