###############################################################
## Packages / Groups / temperature
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'temperature'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer
    ################################################
    ## Sensor
    ################################################

################################################
## Graph
################################################

history_graph:
  temperature:
    name: 'Temperature Graph'
    entities:
      - sensor.climate_master_bedroom_temperature
      - sensor.climate_bathroom_upstairs_temperature
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.plantmonitor1_temperature
      - sensor.plantmonitor2_temperature
      - sensor.plantmonitor3_temperature
      - sensor.plantmonitor4_temperature
    hours_to_show: 24
    refresh: 60

################################################
## Group
################################################

group:
  temperature:
    control: hidden
    entities:
      - sensor.climate_master_bedroom_temperature
      - sensor.climate_bathroom_upstairs_temperature
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.plantmonitor1_temperature
      - sensor.plantmonitor2_temperature
      - sensor.plantmonitor3_temperature
      - sensor.plantmonitor4_temperature
      - history_graph.temperature_graph
