###############################################################
## Packages / Groups / temperature
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'temperature'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.temperature:
      <<: *customize
      friendly_name: "Temperature"
      icon: mdi:thermometer

    ################################################
    ## Sensor
    ################################################

    sensor.openmqttgateway1_temperature:
      <<: *customize
      friendly_name: "Temperature Living Room"
      hidden: false
      icon: mdi:thermometer

    sensor.openmqttgateway2_temperature:
      <<: *customize
      friendly_name: "Temperature Geek Room"
      hidden: false
      icon: mdi:thermometer

################################################
## Group
################################################

group:
  temperature:
    control: hidden
    entities:
      - sensor.openmqttgateway2_temperature
      - sensor.openmqttgateway1_temperature
