################################################################
## Packages / Front Porch Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'back_porch_light'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.back_porch_timer:
      <<: *customize
      friendly_name: "Back Porch Timer"

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.back_porch_expected_state:
      <<: *customize
      friendly_name: "Back Porch Expected State"
      device_class: light
      hidden: true

    ################################################
    ## Input Select
    ################################################

    input_select.back_porch_time_night_off:
      <<: *customize
      friendly_name: "Back Porch Night Time Off"

    input_select.back_porch_time_morning_on:
      <<: *customize
      friendly_name: "Back Porch Morning Time On"

    ################################################
    ## Script
    ################################################

    script.back_porch_light:
      <<: *customize
      friendly_name: "Back Porch Light"
      hidden: true
      icon: mdi:lightbulb

################################################
## Group
################################################

group:
  back_porch_timers:
    control: hidden
    entities:
      - automation.back_porch_timer
      - input_select.back_porch_time_night_off
      - input_select.back_porch_time_morning_on
      - binary_sensor.back_porch_expected_state


################################################
## Automation
################################################

automation:
  - alias: back_porch_timer
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: sensor.time
    condition:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ is_state('input_select.back_porch_time_night_off', trigger.to_state.state) }}"
          - condition: template
            value_template: "{{ is_state('input_select.back_porch_time_morning_on', trigger.to_state.state) }}"
    action:
      - service: script.back_porch_light

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      back_porch_expected_state:
        value_template: >-
          {% set time_now = states('sensor.time').replace(':', '.')|float %}
          {% set time_on = states('input_select.back_porch_time_night_off').replace(':', '.')|float %}
          {% set time_off = states('input_select.back_porch_time_night_off').replace(':', '.')|float %}
          {% set time_off = states('input_select.back_porch_time_night_off').replace(':', '.')|float %}
          {% set time_on = states('input_select.back_porch_time_morning_on').replace(':', '.')|float %}
          {{ not time_off <= time_now < time_on }}

################################################
## Input Select
################################################

input_select:
  back_porch_time_night_off:
    initial: '22:00'
    options:
      - '18:00'
      - '18:30'
      - '19:00'
      - '19:30'
      - '20:00'
      - '20:30'
      - '21:00'
      - '21:30'
      - '22:00'
      - '22:30'
      - '23:00'

  back_porch_time_morning_on:
    initial: '06:00'
    options:
      - '05:00'
      - '05:30'
      - '06:00'
      - '06:30'
      - '07:00'
      - '07:30'
      - '08:00'
      - '08:30'
      - '09:00'

################################################
## Script
################################################

script:
  back_porch_light:
    sequence:
      - service: script.light_control
        data_template:
          entity_id: light.back_porch
          state: "{{ states('binary_sensor.back_porch_expected_state') }}"
          brightness: 200
