################################################################
## Packages / Lights Forgotten
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'automation_light_forgotten'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.lights_forgotten_time_night_off:
      <<: *customize
      friendly_name: "Forgotten Lights Timer Night Off"
      icon: mdi:lightbulb
    automation.lights_forgotten_time_morning_off:
      <<: *customize
      friendly_name: "Forgotten Lights Timer Morning Off"
      icon: mdi:lightbulb

    ################################################
    ## Input Select
    ################################################

    input_datetime.lights_forgotten_time_night_off:
      <<: *customize
      friendly_name: "Forgotten Lights Night Time Off"

    input_datetime.lights_forgotten_time_morning_off:
      <<: *customize
      friendly_name: "Forgotten Lights Morning Time Off"

    ################################################
    ## Group
    ################################################

    group.timer_lights_forgotten:
      <<: *customize
      friendly_name: "Automation Forgotten Lights"
      icon: mdi:lightbulb

################################################
## Group
################################################

group:
  timer_lights_forgotten:
    control: hidden
    entities:
      - automation.lights_forgotten_time_night_off
      - input_datetime.lights_forgotten_time_night_off
      - automation.lights_forgotten_time_morning_off
      - input_datetime.lights_forgotten_time_morning_off

################################################
## Automation
################################################

automation:
  - alias: lights_forgotten_time_night_off
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_forgotten_time_night_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: light.turn_off
        entity_id:
          - light.floalt_panel_ws_60x60
          - light.tradfri_bulb_e14_w_opch_400lm_2
          - light.tradfri_bulb_e14_w_opch_400lm_3
          - light.tradfri_bulb_e27_cws_opal_600lm
          - light.tradfri_bulb_e27_w_opal_1000lm
          - light.tradfri_bulb_e27_w_opal_1000lm_4
          - light.tradfri_bulb_e27_ws_clear_950lm_5
          - light.tradfri_bulb_e27_ws_clear_950lm_6
          - light.tradfri_bulb_e27_ws_opal_980lm_3
          - light.tradfri_bulb_e27_ws_opal_980lm_6
          - light.tradfri_bulb_e27_ws_opal_980lm_7
          - light.tradfri_bulb_e27_ws_opal_980lm_8
          - light.tradfri_bulb_e27_ws_opal_980lm_9
          - light.sonoffs201
          - light.sonoffs202
          - light.rgb_christmas_tree
          - light.onboard_led_christmas_tree
          - light.blue_balls
          - light.onboard_led_blue_balls

  - alias: lights_forgotten_time_morning_off
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_decorative_time_morning_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: sun
        event: sunrise
        offset: '-00:15:00'
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: sun
          before: sunrise
          after_offset: '-00:01:00'
    action:
      - service: light.turn_off
        entity_id:
          - light.floalt_panel_ws_60x60
          - light.tradfri_bulb_e14_w_opch_400lm_2
          - light.tradfri_bulb_e14_w_opch_400lm_3
          - light.tradfri_bulb_e27_cws_opal_600lm
          - light.tradfri_bulb_e27_w_opal_1000lm
          - light.tradfri_bulb_e27_w_opal_1000lm_4
          - light.tradfri_bulb_e27_ws_clear_950lm_5
          - light.tradfri_bulb_e27_ws_clear_950lm_6
          - light.tradfri_bulb_e27_ws_opal_980lm_3
          - light.tradfri_bulb_e27_ws_opal_980lm_6
          - light.tradfri_bulb_e27_ws_opal_980lm_7
          - light.tradfri_bulb_e27_ws_opal_980lm_8
          - light.tradfri_bulb_e27_ws_opal_980lm_9
          - light.sonoffs201
          - light.sonoffs202
          - light.rgb_christmas_tree
          - light.onboard_led_christmas_tree
          - light.blue_balls
          - light.onboard_led_blue_balls

################################################
## Input Date/time
################################################

input_datetime:
  lights_forgotten_time_night_off:
    has_time: true
    initial: '23:30'
  lights_forgotten_time_morning_off:
    has_time: true
    initial: '08:00'
