################################################################
## Packages / Lights Decorative
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'automation_light_decorative'


    ################################################
    ## Automation
    ################################################

    automation.lights_decorative_time_night_on:
      <<: *customize
      friendly_name: "Decorative Lights Timer On"
      icon: mdi:lightbulb
    automation.lights_decorative_time_night_off:
      <<: *customize
      friendly_name: "Decorative Lights Timer Off"
      icon: mdi:lightbulb

    ################################################
    ## Input Select
    ################################################

    input_datetime.lights_decorative_time_night_off:
      <<: *customize
      friendly_name: "Decorative Lights Night Time Off"

    input_datetime.lights_decorative_time_morning_on:
      <<: *customize
      friendly_name: "Decorative Lights Morning Time On"

    ################################################
    ## Group
    ################################################

    group.timer_lights_decorative:
      <<: *customize
      friendly_name: "Automation Decorative Lights"
      icon: mdi:lightbulb

################################################
## Group
################################################

group:
  timer_lights_decorative:
    control: hidden
    entities:
      - automation.lights_decorative_time_night_off
      - input_datetime.lights_decorative_time_night_off
      - automation.lights_decorative_time_night_on
      - input_datetime.lights_decorative_time_morning_on

################################################
## Automation
################################################

automation:
  - alias: lights_decorative_time_night_off
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_decorative_time_night_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: sun
        event: sunrise
        offset: '-00:10:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.tradfri_bulb_e27_ws_opal_980lm_4
          - light.tradfri_bulb_e27_ws_opal_980lm_5
          - light.tradfri_bulb_e14_ws_opal_400lm_7
          - light.christmas_star

  - alias: lights_decorative_time_night_on
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_decorative_time_morning_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: sun
        event: sunset
        offset: '-00:10:00'
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: sun
          before: sunrise
          after_offset: '-00:01:00'
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.tradfri_bulb_e27_ws_opal_980lm_4
            - light.tradfri_bulb_e27_ws_opal_980lm_5
            - light.tradfri_bulb_e14_ws_opal_400lm_7
            - light.christmas_star
          brightness: '254'
          color_temp: '454'
################################################
## Input Date/time
################################################

input_datetime:
  lights_decorative_time_night_off:
    has_time: true
    initial: '22:22'
  lights_decorative_time_morning_on:
    has_time: true
    initial: '05:59'
