################################################################
## Packages / Lights Exterior
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'automation_light_exterior'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.lights_exterior_time_night_on:
      <<: *customize
      friendly_name: "Exterior Lights Timer On"
      icon: mdi:lightbulb
    automation.lights_exterior_time_night_off:
      <<: *customize
      friendly_name: "Exterior Lights Timer Off"
      icon: mdi:lightbulb

    ################################################
    ## Input Select
    ################################################

    input_datetime.lights_exterior_time_night_off:
      <<: *customize
      friendly_name: "Exterior Lights Night Time Off"

    input_datetime.lights_exterior_time_morning_on:
      <<: *customize
      friendly_name: "Exterior Lights Morning Time On"

    ################################################
    ## Group
    ################################################

    group.timer_lights_exterior:
      <<: *customize
      friendly_name: "Automation Exterior Lights"
      icon: mdi:lightbulb

################################################
## Group
################################################

group:
  timer_lights_exterior:
    control: hidden
    entities:
      - automation.lights_exterior_time_night_off
      - input_datetime.lights_exterior_time_night_off
      - automation.lights_exterior_time_night_on
      - input_datetime.lights_exterior_time_morning_on

################################################
## Automation
################################################

automation:
  - alias: lights_exterior_time_night_off
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_exterior_time_night_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: sun
        event: sunrise
        offset: '-00:15:00'
    action:
      - service: homeassistant.turn_off
        entity_id: group.back_porch

  - alias: lights_exterior_time_night_on
    trigger:
      - platform: template
        value_template: "{{ states.sensor.time.state == (states.input_datetime.lights_exterior_time_morning_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
      - platform: sun
        event: sunset
        offset: '-00:15:00'
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: sun
          before: sunrise
          after_offset: '-00:01:00'
    action:
      - service: light.turn_on
        data:
          entity_id: group.back_porch
          brightness_pct: '40'

################################################
## Input Date/time
################################################

input_datetime:
  lights_exterior_time_night_off:
    has_time: true
    initial: '22:35'
  lights_exterior_time_morning_on:
    has_time: true
    initial: '05:45'
