################################################################
## Packages / Plant Monitoring
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notification_plant_monitoring'

    ################################################
    ## Alerts
    ################################################

    alert.plant_monitors:
      <<: *customize
      friendly_name: "Notification Plant Monitoring"

################################################
## Alerts
################################################

alert:
  plant_monitors:
    name: "\ud83c\udf31 Your plants needs your attention."
    done_message: "\ud83d\udc4d Your plants have been cared for. "
    entity_id: group.plants
    state: 'problem'
    repeat:
      - 60
      - 240
      - 480
    skip_first: True
    notifiers:
      - telegram_house
