################################################################
## Packages / Notification Low Battery
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notification_utility'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.forward_persistent_notifications:
      <<: *customize
      friendly_name: "Forward Persistent Notifications"
      icon: mdi:message-text

    automation.startup_notification:
      <<: *customize
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *customize
      friendly_name: "Update Notification"
      icon: mdi:message-text

    ################################################
    ## Sensors
    ################################################

################################################
## Sensor
################################################

################################################
## Notification
################################################
automation:
  - alias: forward_persistent_notifications
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: persistent_notification
          service: create
    action:
      - service: notify.telegram_house
        data_template:
          title: >-
            {% set title = trigger.event.data.service_data.title %}
            {{ title }}
          message: >-
            {% set message = trigger.event.data.service_data.message %}
            {{ message }}

  - alias: startup_notification
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        seconds: '/30'
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.startup_notification
      - service: notify.telegram_house
        data_template:
          message: >-
            {% set message = [
              "\ud83c\udfe1 Home Assistant was restarted at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}",
              "\ud83c\udfe1 Home Assistant online at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}"
            ] %}
            {{ message|random }}
  - alias: update_notification
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ha_github_version
      - platform: state
        entity_id: sensor.ha_pypi_version
    condition:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.state != states('sensor.ha_version') }}
      - condition: template
        value_template: >-
          {{ trigger.to_state.state != 'unknown' }}
    action:
      - service: notify.telegram_house
        data_template:
          message: >-
            "\u2618 Home Assistant {{ trigger.to_state.state }} is now available on {{ trigger.to_state.name.split(' ')[0] }}."
