###############################################################################
# Packages / Broadlink Sp3
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'broadlink'

  ################################################
  ## Group
  ################################################

  ################################################
  ## Script
  ################################################

  ################################################
  ## Automation
  ################################################

  ################################################
  ## Input Select
  ################################################

  ################################################
  ## Sensor
  ################################################

###############################################################################
# Devices
###############################################################################

  ################################################
  ## Group
  ################################################


  ################################################
  ## Switch
  ################################################

switch:
  - platform: broadlink
    host: '10.0.210.101'
    mac: '78:0F:77:EB:91:97'
    type: 'sp3'
