################################################################
## Packages / Device Trackers
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:
    ################################################
    ## Group
    ################################################


    ################################################
    ## Sensor
    ################################################


################################################
## Group
################################################

################################################
## Device Trackers
################################################

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: false
    waypoint_whitelist:
      - landrash

  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    home_interval: 10
    exclude:
     - 192.168.0.1
################################################
## Sensor
################################################

sensor:
  - platform: mqtt
    state_topic: "owntracks/hassHibbleLandrashMobile/landrash"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery Nexus5X"

  - platform: mqtt
    state_topic: "owntracks/hassHibbleJoJoMobile/a3Jojo"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery SamsungA3"

#  - platform: template
#    sensors:
#      xiaomi_vacuum_cleaner_battery:
#        friendly_name: "Xiaomi Vacuum Cleaner Battery"
#        entity_id: xiaomi_vacuum_cleaner
#        unit_of_measurement: '%'
#        value_template: "{{ states.xiaomi_vacuum_cleaner.attributes.battery_level }}"
#        icon_template: "{{ state.xiaomi_vacuum_cleaner.attributes.battery_icon if is_state('vacuum.xiaomi_vacuum_cleaner.attributes.status', 'Charging') else 'mdi:battery' }}"
