################################################################
## Packages / Device Trackers
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:
    ################################################
    ## Group
    ################################################


    ################################################
    ## Sensor
    ################################################


################################################
## Group
################################################

################################################
## Device Trackers
################################################

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: false
    waypoint_whitelist:
      - landrash

  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password

################################################
## Sensor
################################################

sensor:
  - platform: mqtt
    state_topic: "owntracks/hassHibbleLandrashMobile/landrash"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery Nexus5X"

  - platform: mqtt
    state_topic: "owntracks/hassHibbleJoJoMobile/a3Jojo"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery SamsungA3"
