################################################################
## Packages / Device Trackers
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:
    ################################################
    ## Group
    ################################################


    ################################################
    ## Sensor
    ################################################


################################################
## Group
################################################

################################################
## Device Trackers
################################################

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: false
    waypoint_whitelist:
      - landrash

  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password

################################################
## Camera
################################################

#camera:
#  - platform: generic
#    name: 'Landrash Map'
#    still_image_url: !secret google_map_landrash
#    limit_refetch_to_url_change: true

#  - platform: generic
#    name: 'Jojo Map'
#    still_image_url: !secret google_map_jojo
#    limit_refetch_to_url_change: true

################################################
## Sensor
################################################

sensor:
  - platform: mqtt
    state_topic: "owntracks/hassHibbleLandrashMobile/landrash"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery A1"

  - platform: mqtt
    state_topic: "owntracks/hassHibbleJoJoMobile/a3Jojo"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    name: "Battery Samsung A3"

  - platform: google_travel_time
    name: 'Landrash To Home'
    api_key: !secret google_api_key
    origin: device_tracker.hasshibblelandrashmobile_landrash
    destination: zone.home

  - platform: google_travel_time
    name: 'Jojo To Home'
    api_key: !secret google_api_key
    origin: device_tracker.hasshibblejojomobile_a3jojo
    destination: zone.home

################################################
## Map
################################################

map:
