################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:

################################################
## HTTP
################################################

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
