################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
# Authentication provider
  auth_providers:
   - type: homeassistant

################################################
## HTTP
################################################

http:
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
