################################################################
## Packages / Logbook
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:

################################################
## Logbook
################################################

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
    domains:
      - sun
