################################################################
## Packages / Logbook
################################################################

################################################
## Customize
################################################

homeassistant:
#  customize:

################################################
## Logbook
################################################

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
      - automation.battery_notification
      - automation.battery_notification_clear
      - automation.battery_sensor_from_battery_attribute
      - automation.battery_sensor_from_battery_level_attribute
      - automation.battery_sensor_from_battery_numeric_attribute
      - sensor.fibaro_system_fgd212_dimmer_2_exporting
      - sensor.fibaro_system_fgd212_dimmer_2_power_management
      - sensor.fibaro_system_fgd212_dimmer_2
    domains:
      - sun
      - weather
