################################################################
## Packages / Groups / Media Players
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/media_players'

    ################################################
    ## Group
    ################################################


    ################################################
    ## Media Players
    ################################################

    media_player.kodi_master_bedroom_host:
      <<: *customize
      friendly_name: "Kodi Sovrum"

################################################
## Group
################################################
group:
  radio:
    control: hidden
    entities:
    - input_select.chromecast_radio_station
    - input_text.custom_station
    - input_select.chromecast_radio_speakers
    - input_number.volume_radio
    - script.play_chromecast_radio
    - script.stop_chromecast_radio

################################################
## Inputs
################################################

input_select:
  chromecast_radio_station:
    name: 'Select Radio Station'
    options:
      - Lugna Favoriter
      - Mix Megapol
      - NRJ
      - Playdio
      - Radio 107,5
      - Rix FM
      - Rock Klasisker
      - Vinyl 107,5
      - Sveriges Radio P1
      - Custom Station
    icon: mdi:radio

  chromecast_radio_speakers:
    name: 'Select Speakers'
    options:
      - Kitchen
      - Office
      - Bedroom
      - LivingRoom
      - All
    initial: LivingRoom
    icon: mdi:speaker-wireless

input_text:
  custom_station:
    name: Radio URL
    icon: mdi:link-variant

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    initial: 0.3
    min: 0
    max: 1
    step: 0.05

################################################
## Media Players
################################################

cast:
  media_player:
  - host: !secret chromecast_living_room_host
  - host: !secret chromecast_master_bedroom_host
  - host: !secret google_home_mini_kitchen
  - host: !secret google_home_mini_office

media_player:
  - platform: kodi
    host: !secret kodi_master_bedroom_host
    name: kodi_master_bedroom_host
    turn_on_action:
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby

  ################################################
  ## Script
  ################################################

script:
  update_library:
    alias: Update Kodi Library
    sequence:
      - alias: Call Kodi update
        service: media_player.kodi_call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.Scan
  play_chromecast_radio:
    alias: Cast Selected Radio on Chromecast Speakers
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "LivingRoom") %} media_player.living_room_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom") %} media_player.master_bedroom_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.koks_hogtalare
            {% elif is_state("input_select.chromecast_radio_speakers", "Office") %} media_player.kontor
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
          volume_level: '{{  states.input_number.volume_radio.state  }}'
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "LivingRoom") %} media_player.living_room_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom") %} media_player.master_bedroom_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.koks_hogtalare
            {% elif is_state("input_select.chromecast_radio_speakers", "Office") %} media_player.kontor
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
          media_content_id: >
            {% if is_state("input_select.chromecast_radio_station", "Lugna Favoriter") %} http://stream-ice.mtgradio.com:8080/stat_lugna_favoriter.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Mix Megapol") %} http://194.16.21.227/mix_se_mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "NRJ") %} http://194.16.21.227/nrj_se_mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Playdio") %} http://media.playdio.se/listen.pls
            {% elif is_state("input_select.chromecast_radio_station", "Radio 107,5") %} http://194.16.21.227/1075_se_mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Rix FM") %} http://stream-ice.mtgradio.com:8080/stat_rix_fm.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Rock Klasisker") %} http://194.16.21.227/rock_se_mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Vinyl 107,5") %} http://194.16.21.227/vinyl_se_mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Sveriges Radio P1") %} http://sverigesradio.se/topsy/direkt/132-hi-mp3.m3u
            {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} {{states.input_text.custom_station.state}}
            {% endif %}
          media_content_type: 'audio/mp4'

  stop_chromecast_radio:
    alias: Stop Playing Radio on ChromeCast
    sequence:
      - service: media_player.turn_off
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "LivingRoom") %} media_player.living_room_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom") %} media_player.master_bedroom_tv
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.koks_hogtalare
            {% elif is_state("input_select.chromecast_radio_speakers", "Office") %} media_player.kontor
            {% elif is_state("input_select.chromecast_radio_speakers", "All") %} media_player.home_group
            {% endif %}
