################################################################
## Packages / Groups / Media Players
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/media_players'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.media_players:
      <<: *customize
      friendly_name: "Media Players"

################################################
## Group
################################################
group:
  media_players:
    control: hidden
    entities:
      - media_player.living_room_tv
      - media_player.master_bedroom_tv

################################################
## Media Players
################################################

cast:
  media_player:
  - host: !secret chromecast_living_room_host
  - host: !secret chromecast_master_bedroom_host
