################################################################
## Packages / Network Devices
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Group
    ################################################

    group.network_devices_source:
      friendly_name: "Network Device Sources"

    group.network_devices:
      friendly_name: "Network Devices"

    ################################################
    ## Device Tracker
    ################################################

    device_tracker.net_chromecast_living_room:
      friendly_name: "Chromecast (Living Room)"
      hidden: true

    device_tracker.net_chromecast_master_bedroom:
      friendly_name: "Chromecast (Master Bedroom)"
      hidden: true

    binary_sensor.tradfrigateway:
      friendly_name: "IKEA Trådfri"
      hidden: true

    device_tracker.net_raspberry_pi:
      friendly_name: "Raspberry Pi"
      hidden: true

    ################################################
    ## Sensor
    ################################################

    sensor.net_chromecast_living_room:
      friendly_name: "Chromecast (Living Room)"

    sensor.net_chromecast_master_bedroom:
      friendly_name: "Chromecast (Master Bedroom)"

    sensor.net_ikea_tradfri:
      friendly_name: "IKEA Trådfri"

    sensor.net_raspberry_pi:
      friendly_name: "Raspberry Pi"

    net_xiaomi_miio_vacuum:
      friendly_name: "Xiaomi Miio Vacuum"

################################################
## Group
################################################

group:
  network_devices_source:
    control: hidden
    entities:
      - device_tracker.net_chromecast_living_room
      - device_tracker.net_chromecast_master_bedroom
      - binary_sensor.tradfrigateway
      - device_tracker.net_raspberry_pi
      - binary_sensor.openmqttgateway1
      - binary_sensor.openmqttgateway2
      - device_tracker.openmqttgateway1
      - device_tracker.openmqttgateway2
      - device_tracker.xiaomi_miio_vacuum

  network_devices:
    control: hidden
    entities:
      - sensor.net_chromecast_living_room
      - sensor.net_chromecast_master_bedroom
      - sensor.net_ikea_tradfri
      - sensor.net_raspberry_pi
      - sensor.net_openmqttgateway1
      - sensor.net_openmqttgateway2
      - sensor.net_xiaomi_miio_vacuum

  zwave:
    control: hidden
    entities:
      - zwave.fibaro_system_fgwpef_wall_plug
      - zwave.fibaro_system_fgms001_motion_sensor
      - zwave.fibaro_system_fgd212_dimmer_2
      - zwave.zwaveme_zme_uzb1_usb_stick
      - zwave.danfoss_z_thermostat_014g0013
      - zwave.danfoss_z_thermostat_014g0013_2

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      net_chromecast_living_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_chromecast_living_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_chromecast_living_room', 'home') else 'mdi:alert-circle' }}"

      net_chromecast_master_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_chromecast_master_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_chromecast_master_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_ikea_tradfri:
        value_template: "{{ 'online' if is_state('binary_sensor.tradfrigateway', 'on') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('binary_sensor.tradfrigateway', 'on') else 'mdi:alert-circle' }}"

      net_raspberry_pi:
        value_template: "{{ 'online' if is_state('device_tracker.net_raspberry_pi', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_raspberry_pi', 'home') else 'mdi:alert-circle' }}"

      net_openmqttgateway1:
        value_template: "{{ 'online' if is_state('binary_sensor.openmqttgateway1', 'on') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('binary_sensor.openmqttgateway1', 'on') else 'mdi:alert-circle' }}"

      net_openmqttgateway2:
        value_template: "{{ 'online' if is_state('binary_sensor.openmqttgateway2', 'on') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('binary_sensor.openmqttgateway2', 'on') else 'mdi:alert-circle' }}"

      net_xiaomi_miio_vacuum:
        value_template: "{{ 'online' if is_state('device_tracker.xiaomi_miio_vacuum', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.xiaomi_miio_vacuum', 'home') else 'mdi:alert-circle' }}"

#  - platform: shodan
#    api_key: !secret shodan_api_key
#    query: 'home-assistant'

################################################
## Sensor
################################################


binary_sensor:
  - platform: ping
    host: !secret tradfri_host
    name: tradfrigateway
