################################################################
## Packages / Network Device Monitoring
################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'network_device_monitoring'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Device Tracker
################################################

    binary_sensor.net_chromecast_living_room:
      <<: *customize
      friendly_name: "Chromecast (Living Room)"

    binary_sensor.net_chromecast_master_bedroom:
      <<: *customize
      friendly_name: "Chromecast (Master Bedroom)"

    binary_sensor.net_google_home_mini_kitchen:
      <<: *customize
      friendly_name: "Google Home Mini (Kitchen)"

    binary_sensor.net_google_home_mini_office:
      <<: *customize
      friendly_name: "Google Home Mini (Office)"

    binary_sensor.net_kodi_master_bedroom:
      <<: *customize
      friendly_name: "Kodi (Master Bedroom)"

    binary_sensor.net_tradfrigateway:
      <<: *customize
      friendly_name: "IKEA Tradfri Gateway"

    binary_sensor.xiaomi_miio_vacuum:
      <<: *customize
      friendly_name: "Xiaomi Miio Vacuum"

################################################
## Group
################################################

    group.network_devices:
      <<: *customize
      friendly_name: "Network Devices"

################################################
## Group
################################################

group:
  network_devices:
    control: hidden
    entities:
      - binary_sensor.net_tradfrigateway
      - binary_sensor.net_chromecast_living_room
      - binary_sensor.net_chromecast_master_bedroom
      - binary_sensor.net_kodi_master_bedroom
      - binary_sensor.xiaomi_miio_vacuum
      - binary_sensor.rgb_christmas_tree_status
      - binary_sensor.net_google_home_mini_kitchen
      - binary_sensor.net_google_home_mini_office
      - history_graph.network_wired
      - history_graph.network_wireless

  zwave:
    control: hidden
    entities:
      - zwave.fibaro_system_fgwpef_wall_plug
      - zwave.fibaro_system_fgms001_motion_sensor
      - zwave.fibaro_system_fgd212_dimmer_2
      - zwave.zwaveme_zme_uzb1_usb_stick
      - zwave.danfoss_z_thermostat_014g0013
      - zwave.danfoss_z_thermostat_014g0013_2
      - zwave.danfoss_z_thermostat_014g0013_3
      - history_graph.zwave_devices

################################################
## Sensor
################################################

#sensor:
#  - platform: snmp
#      host: !secret unifi_ubiquiti_ap1_host
#      community: !secret unifi_community

################################################
## Sensor
################################################

history_graph:
  network_wired:
    name: 'Network Wired'
    entities:
      - binary_sensor.net_tradfrigateway
    hours_to_show: 72
    refresh: 60
  network_wireless:
    name: 'Network Wireless'
    entities:
      - binary_sensor.net_chromecast_living_room
      - binary_sensor.net_chromecast_master_bedroom
      - binary_sensor.net_kodi_master_bedroom
      - binary_sensor.xiaomi_miio_vacuum
      - binary_sensor.rgb_christmas_tree_status
      - binary_sensor.net_google_home_mini_kitchen
      - binary_sensor.net_google_home_mini_office
    hours_to_show: 72
    refresh: 60
  zwave:
    name: 'Z-Wave Devices'
    entities:
      - zwave.fibaro_system_fgwpef_wall_plug
      - zwave.fibaro_system_fgms001_motion_sensor
      - zwave.fibaro_system_fgd212_dimmer_2
      - zwave.zwaveme_zme_uzb1_usb_stick
      - zwave.danfoss_z_thermostat_014g0013
      - zwave.danfoss_z_thermostat_014g0013_2
      - zwave.danfoss_z_thermostat_014g0013_3
    hours_to_show: 72
    refresh: 60

################################################
## Sensor
################################################

binary_sensor:
  - platform: ping
    host: !secret tradfri_host
    name: net_tradfrigateway
  - platform: ping
    host: !secret vacuum_miio_host
    name: xiaomi_miio_vacuum
  - platform: ping
    host: !secret chromecast_living_room_host
    name: net_chromecast_living_room
  - platform: ping
    host: !secret chromecast_master_bedroom_host
    name: net_chromecast_master_bedroom
  - platform: ping
    host: !secret kodi_master_bedroom_host
    name: net_kodi_master_bedroom
  - platform: ping
    host: !secret google_home_mini_office
    name: net_google_home_mini_office
  - platform: ping
    host: !secret google_home_mini_kitchen
    name: net_google_home_mini_kitchen
