################################################################
## Packages / Network Device Monitoring
################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'network_device_monitoring'

################################################
## Device Tracker
################################################

    binary_sensor.net_chromecast_living_room:
      <<: *customize
      friendly_name: "Chromecast (Living Room)"

    binary_sensor.net_chromecast_master_bedroom:
      <<: *customize
      friendly_name: "Chromecast (Master Bedroom)"

    binary_sensor.net_google_home_mini_kitchen:
      <<: *customize
      friendly_name: "Google Home Mini (Kitchen)"

    binary_sensor.net_google_home_mini_office:
      <<: *customize
      friendly_name: "Google Home Mini (Office)"

    binary_sensor.net_kodi_master_bedroom:
      <<: *customize
      friendly_name: "Kodi (Master Bedroom)"

    binary_sensor.net_tradfrigateway:
      <<: *customize
      friendly_name: "IKEA Tradfri Gateway"

    binary_sensor.xiaomi_miio_vacuum:
      <<: *customize
      friendly_name: "Xiaomi Miio Vacuum"

################################################
## Group
################################################

################################################
## Group
################################################

################################################
## Sensor
################################################

#sensor:
#  - platform: snmp
#      host: !secret unifi_ubiquiti_ap1_host
#      community: !secret unifi_community


################################################
## Sensor
################################################

binary_sensor:
  - platform: ping
    host: !secret tradfri_host
    name: net_tradfrigateway
  - platform: ping
    host: !secret vacuum_miio_host
    name: xiaomi_miio_vacuum
  - platform: ping
    host: !secret chromecast_living_room_host
    name: net_chromecast_living_room
  - platform: ping
    host: !secret chromecast_master_bedroom_host
    name: net_chromecast_master_bedroom
  - platform: ping
    host: !secret kodi_master_bedroom_host
    name: net_kodi_master_bedroom
  - platform: ping
    host: !secret google_home_mini_office
    name: net_google_home_mini_office
  - platform: ping
    host: !secret google_home_mini_kitchen
    name: net_google_home_mini_kitchen
