################################################################
## Packages / Pihole
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'pihole'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
################################################
## Groups
################################################

    group.pihole:
      <<: *customize
      friendly_name: "Pihole"

################################################
## Sensors
################################################


################################################
## Groups
################################################

group:
  pihole:
    control: hidden
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_domains_blocked
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_seen_clients

################################################
## Sensors
################################################

sensor:
  - platform: pi_hole
    host: localhost
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
      - clients_ever_seen
