################################################################
## Packages / Plants
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plants'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        hidden: true

    ################################################
    ## Group
    ################################################

    group.plants:
      <<: *customize
      friendly_name: "Plants"
      hidden: false

    group.plants_source:
      <<: *customize
      friendly_name: "Plants sources"

    ################################################
    ## Plants
    ################################################

    plant.plant_1:
      <<: *customize
      friendly_name: "Spathiphyllum Kochii"
      hidden: false

    plant.plant_2:
      <<: *customize
      friendly_name: "Spathiphyllum Gold Cupid"
      hidden: false

    plant.plant_3:
      <<: *customize
      friendly_name: "Capsicum Bomba red"
      hidden: false

    plant.plant_4:
      <<: *customize
      friendly_name: "Cherry Tomato"
      hidden: false


    ################################################
    ## Sensors
    ################################################

    sensor.plantmonitor1_temperature:
      <<: *customize
      friendly_name: "Temperature Spathiphyllum Kochii"
      hidden: false

    sensor.plantmonitor2_temperature:
      <<: *customize
      friendly_name: "Temperature Spathiphyllum Gold Cupid"
      hidden: false

    sensor.plantmonitor3_temperature:
      <<: *customize
      friendly_name: "Temperature Capsicum Bomba red"
      hidden: false

    sensor.plantmonitor4_temperature:
      <<: *customize
      friendly_name: "Temperature Cherry Tomato"
      hidden: false

################################################
## Group
################################################
group:
  plants:
    control: hidden
    entities:
      - plant.plant_1
      - plant.plant_2
      - plant.plant_3
      - plant.plant_4

  plants_source:
    control: hidden
    entities:
    - sensor.plantmonitor1_moisture
    - sensor.plantmonitor1_conductivity
    - sensor.plantmonitor2_moisture
    - sensor.plantmonitor2_conductivity
    - sensor.plantmonitor3_moisture
    - sensor.plantmonitor3_conductivity
    - sensor.plantmonitor4_moisture
    - sensor.plantmonitor4_conductivity

################################################
## Sensors
################################################

sensor:
  - platform: miflora
    mac: !secret plantmonitor1
    name: plantmonitor1
    median: 3
  - platform: miflora
    mac: !secret plantmonitor2
    name: plantmonitor2
    median: 3
  - platform: miflora
    mac: !secret plantmonitor3
    name: plantmonitor3
    median: 3
  - platform: miflora
    mac: !secret plantmonitor4
    name: plantmonitor4
    median: 3

################################################
## Plants
################################################

plant:
  plant_1:
    sensors:
      moisture: sensor.plantmonitor1_moisture
      battery: sensor.plantmonitor1_battery
      temperature: sensor.plantmonitor1_temperature
      conductivity: sensor.plantmonitor1_conductivity
      brightness: sensor.plantmonitor1_light_intensity
    min_moisture: 20
    max_moisture: 75
    min_battery: 10
    min_conductivity: 225
    min_temperature: 10
  plant_2:
    sensors:
      moisture: sensor.plantmonitor2_moisture
      battery: sensor.plantmonitor2_battery
      temperature: sensor.plantmonitor2_temperature
      conductivity: sensor.plantmonitor2_conductivity
      brightness: sensor.plantmonitor2_light_intensity
    min_moisture: 20
    max_moisture: 75
    min_battery: 10
    min_conductivity: 225
    min_temperature: 10
  plant_3:
    sensors:
      moisture: sensor.plantmonitor3_moisture
      battery: sensor.plantmonitor3_battery
      temperature: sensor.plantmonitor3_temperature
      conductivity: sensor.plantmonitor3_conductivity
      brightness: sensor.plantmonitor3_light_intensity
    min_moisture: 2
    max_moisture: 75
    min_battery: 10
    min_conductivity: 105
    min_temperature: 10
  plant_4:
    sensors:
      moisture: sensor.plantmonitor4_moisture
      battery: sensor.plantmonitor4_battery
      temperature: sensor.plantmonitor4_temperature
      conductivity: sensor.plantmonitor4_conductivity
      brightness: sensor.plantmonitor4_light_intensity
    min_moisture: 2
    max_moisture: 75
    min_battery: 10
    min_conductivity: 105
    min_temperature: 10
