################################################################
## Packages / Recorder
################################################################

################################################
## Customize
################################################

homeassistant:

################################################
## Recorder & History
################################################
recorder:
  purge_interval: 2
  purge_keep_days: 14
  exclude:
    domains:
      - camera
      - media_player
      - sun
    entities:
      - automation.startup_notification
      - sensor.date
      - sensor.ha_github_version
      - sensor.ha_pypi_version
      - sensor.ha_startup_time
      - sensor.ha_version
      - sensor.secrets
      - sensor.time
