################################################################
## Packages / Ruuvitag
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ruuvi'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
################################################
## Groups
################################################

################################################
## Sensors
################################################

################################################
## Groups
################################################

################################################
## Sensors
################################################

sensor:
  - platform: ruuvitag
    beacons:
      master_bedroom:
        mac: 'E8:29:B9:1A:4F:3A'
