################################################################
## Packages / MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'sonoff'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## MQTT
################################################
light:
  - platform: mqtt
    name: sonoffs201
    state_topic: "stat/sonoffs201/POWER"
    command_topic: "cmnd/sonoffs201/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: sonoffs202
    state_topic: "stat/sonoffs202/POWER"
    command_topic: "cmnd/sonoffs202/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
