################################################################
## Packages / System
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

    ################################################
    ## Device Tracker
    ################################################

    ################################################
    ## Group
    ################################################

    ################################################
    ## Sensor
    ################################################

    sensor.date:
      <<: *customize
      friendly_name: "System Date"
      icon: mdi:calendar

    binary_sensor.workday_sensor:
      <<: *customize
      friendly_name: "Workday"
      icon: mdi:calendar

    sensor.ha_github_version:
      <<: *customize
      friendly_name: "GitHub Version"
      icon: mdi:github-box

    sensor.ha_pypi_version:
      <<: *customize
      friendly_name: "PyPi Version"
      icon: mdi:language-python

    sensor.ha_startup_time:
      <<: *customize
      friendly_name: "Startup Time"
      icon: mdi:clock-start

    sensor.ha_uptime:
      <<: *customize
      friendly_name: "Upime"
      icon: mdi:clock-start

    sensor.ha_version:
      <<: *customize
      friendly_name: "Installed Version"
      icon: mdi:settings-box

    sensor.time:
      <<: *customize
      friendly_name: "System Time"
      icon: mdi:clock

################################################
## Group
################################################

################################################
## Sensor
################################################

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: uptime

  - platform: template
    sensors:
      ha_startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ as_timestamp((states.automation.startup_notification.attributes|default).last_triggered|default(None))|timestamp_local or 'unknown' }}

  - platform: version
    name: ha_version
    scan_interval: 86400

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name if value_json.tag_name.split('.')|length != 2 else value_json.tag_name ~ '.0' }}
    scan_interval: 1800

  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}
    scan_interval: 1800

  - platform: rpi_power

################################################
## Workday
################################################

binary_sensor:
  - platform: workday
    country: SE

################################################
## DNS & SSL
################################################

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

################################################
## Python scripts
################################################

python_script:

script:
  scan_orphans:
    alias: Scan ungrouped Orphans
    sequence:
      - service: python_script.scan_orphans
        data:
          ignore_items:
            - sensor.ghosts_sensor
            - sensor.orphans_sensor
            - sensor.orphans_badge
          ignore_domains:
            - scene
            - zwave
            - weblink
  light_counter:
    alias: Lights on
    sequence:
      - service: python_script.light_counter
  populate_catchall_group:
    alias: Group ungrouped entities
    sequence:
      - service: python_script.populate_catchall_group

################################################
## Base Components
################################################

discovery:
  ignore:
    - google_cast
    - ikea_tradfri

updater:
  include_used_components: true
