################################################################
## Packages / Trådfri
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'tradfri'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Trådfri Hub
################################################

tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: false
#  api_key: !secret tradfri_api_key
