################################################################
## Packages / Trådfri
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'tradfri'

################################################
## Trådfri Hub
################################################

tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: false
