################################################################
## Packages / Utilities
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'utilities'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.nightly_config_backup:
      <<: *customize
      friendly_name: "Nightly Config Backup"
      icon: mdi:backup-restore

    ################################################
    ## Group
    ################################################

    group.utilities:
      <<: *customize
      friendly_name: "Utilities"
      icon: mdi:script

    ################################################
    ## Script
    ################################################

    script.manual_config_backup:
      <<: *customize
      friendly_name: "Manual Config Backup"
      icon: mdi:backup-restore

    script.reload_config:
      <<: *customize
      friendly_name: "Reload Configuration"
      icon: mdi:refresh

    script.restart_hass:
      <<: *customize
      friendly_name: "Restart Home Assistant"
      icon: mdi:power

################################################
## Group
################################################

group:
  utilities:
    control: hidden
    entities:
      - script.manual_config_backup
      - script.reload_config
      - script.restart_hass
  notifications:
    control: hidden
    entities:
      - persistent_notification.invalid_config


################################################
## Automation
################################################

automation:
  - alias: nightly_config_backup
    initial_state: 'off'
    trigger:
      - platform: time
        at: '03:00:00'
    action:
      - service: shell_command.manual_config_backup

################################################
## Script
################################################

script:
  manual_config_backup:
    sequence:
      - service: shell_command.manual_config_backup

  reload_config:
    sequence:
      - service: homeassistant.reload_core_config

  restart_hass:
    sequence:
      - service: homeassistant.restart

################################################
## Shell Command
################################################

shell_command:
  manual_config_backup: >-
    $HASS_CONFIG/shell_scripts/backup_config.sh
