###############################################################################
# Packages / Trådfri
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'vacuum'

  ################################################
  ## Group
  ################################################
    group.robot_vacuum:
      <<: *customize
      friendly_name: "Battery Alert"
      icon: mdi:steam

  ################################################
  ## Script
  ################################################

  ################################################
  ## Automation
  ################################################

  ################################################
  ## Input Select
  ################################################

  ################################################
  ## Sensor
  ################################################

###############################################################################
# Devices
###############################################################################

  ################################################
  ## Group
  ################################################

group:
  robot_vacuum:
    control: hidden
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - input_select.vacuum_room
      - binary_sensor.vacuum_room
      - sensor.xiaomi_vacuum_cleaner_status

  ################################################
  ## Vacuum
  ################################################

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_miio_host
    token: !secret vacuum_miio_api_key

  ################################################
  ## Input Select
  ################################################

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - All
      - Kitchen
      - Dining Room
      - Living Room

  ################################################
  ## Sensor
  ################################################

sensor:
  - platform: template
    sensors:
      xiaomi_vacuum_cleaner_status:
        friendly_name: "Xiaomi Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"

  ################################################
  ## Script
  ################################################

script:
  vacuum_all:
        alias: "Vacuum All"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16034,19737,26234,29237,1],[19487,29248,26237,32198,1]]
  vacuum_kitchen:
        alias: "Vacuum Kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[12038,27467,16088,32017,1]]
  vacuum_dining_room:
        alias: "Vacuum Dining Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[25316,23644,28916,27044,1]] #Updated
  vacuum_living_room:
        alias: "Vacuum Living Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[18266,19661,23016,25061,1]]

  ###############################################################################
  # Automation
  ###############################################################################
automation:
  - alias: Start Cleaning Room
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "All") %}
            script.vacuum_all
          {% elif is_state("input_select.vacuum_room", "Dining Room") %}
            script.vacuum_dining_room
          {% elif is_state("input_select.vacuum_room", "Kitchen") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Living Room") %}
            script.vacuum_living_room
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
