###############################################################################
# Packages / Trådfri
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'vacuum'

  ################################################
  ## Group
  ################################################
    group.robot_vacuum:
      <<: *customize
      friendly_name: "Vacuum"
      icon: mdi:robot-vacuum

  ################################################
  ## Script
  ################################################

  ################################################
  ## Automation
  ################################################

  ################################################
  ## Input Select
  ################################################

  ################################################
  ## Sensor
  ################################################

###############################################################################
# Devices
###############################################################################

  ################################################
  ## Group
  ################################################

group:
  robot_vacuum:
    control: hidden
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - input_select.vacuum_room
      - sensor.xiaomi_vacuum_cleaner_status
      - camera.vacuum_map

  ################################################
  ## Vacuum
  ################################################

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_miio_host
    token: !secret vacuum_miio_api_key

  ################################################
  ## Input Select
  ################################################

input_select:
  vacuum_room:
    name: Choose a area to clean
    options:
      - Select Input
      - Kitchen
      - Kitchen Counter
      - Dining Room
      - Living Room

  ################################################
  ## Camera / Map
  ################################################

camera:
  - platform: generic
    name: Vacuum Map
    still_image_url: !secret vacuum_miio_map
    content_type: image/png
    framerate: 1

  ################################################
  ## Sensor
  ################################################

sensor:
  - platform: template
    sensors:
      xiaomi_vacuum_cleaner_status:
        friendly_name: "Xiaomi Vacuum Cleaner Status"
        value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"

  ################################################
  ## Script
  ################################################

script:
  vacuum_kitchen:
        alias: "Vacuum Kitchen"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26601,24654,32451,25654,1],[28554,20965,32204,25365,1],[26549,23770,28549,24620,1]]
  vacuum_kitchen_counter:
        alias: "Vacuum Kitchen Counter"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[26601,24654,32451,25654,1]]
  vacuum_dining_room:
        alias: "Vacuum Dining Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[25316,23644,28916,27044,1]]
  vacuum_living_room:
        alias: "Vacuum Living Room"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[22415,19013,26465,26063,1],[26451,18976,28551,23126,1]]

  ###############################################################################
  # Automation
  ###############################################################################
automation:
  - alias: Start Cleaning Room
    hide_entity: True
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Input'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.vacuum_room", "Dining Room") %}
            script.vacuum_dining_room
          {% elif is_state("input_select.vacuum_room", "Kitchen") %}
            script.vacuum_kitchen
          {% elif is_state("input_select.vacuum_room", "Kitchen Counter") %}
            script.vacuum_kitchen_counter
          {% elif is_state("input_select.vacuum_room", "Living Room") %}
            script.vacuum_living_room
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Input"
