################################################################
## Packages / Views
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.automation:
      <<: *customize
      friendly_name: "Automation"
      icon: mdi:settings

    group.cameras:
      <<: *customize
      friendly_name: "Cameras"
      icon: mdi:camcorder

    group.default_view:
      <<: *customize
      friendly_name: "Home"
      icon: mdi:home

    group.household:
      <<: *customize
      friendly_name: "Household"
      icon: mdi:human-greeting

    group.media:
      <<: *customize
      friendly_name: "Media"
      icon: mdi:play-circle-outline

    group.network:
      <<: *customize
      friendly_name: "Network"
      icon: mdi:switch

    group.sensors:
      <<: *customize
      friendly_name: "Sensors"
      icon: mdi:gauge
      hidden: false

    group.zwave:
      <<: *customize
      friendly_name: "Z-Wave Devices"
      icon: mdi:gauge

    group.weather:
      <<: *customize
      friendly_name: "Weather"
      icon: mdi:weather-partlycloudy

    group.all_scripts:
      <<: *customize
      hidden: false

    group.all_automations:
      <<: *customize
      hidden: false

################################################
## Group
################################################

group:
  house:
  #default_view:
    view: yes
    entities:
      - group.bathroom_entry
      - group.back_porch
      - group.entry
      - group.front_porch
      - group.hallway
      - group.kitchen
      - group.laundry_room
      - group.living_room
      - group.master_bedroom
      - group.second_bedroom
      - group.geek_room
      - group.walkin_closet

  household:
    view: yes
    entities:
      - group.family
      - group.guests

  network:
    view: yes
    entities:
      - group.network_devices
      - group.system
      - group.utilities
      - group.zwave
      - group.notifications

  sensors:
    view: yes
    entities:
      - group.batteries
      - group.temperature
      - group.thermostat
      - group.humidity
      - group.motion
      - group.plants
      - group.light_sensors
      - group.power_monitors

  media:
    view: yes
    entities:
      - group.media_players

  automation:
    view: yes
    entities:
      - group.automation_override
      - group.all_automations
      - group.all_scripts
      - group.timer_lights_exterior
      - group.timer_lights_decorative

  weather:
    view: yes
    entities:
      - group.weather_general
      - group.weather_darksky
      - group.weather_wunderground
      - group.weather_yr
      - group.weather_camera
