################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Lock
    ################################################

    ################################################
    ## Thermostat
    ################################################

    ################################################
    ## Sensor
    ################################################

  ################################################
  ## Customize Domain
  ################################################

################################################
## Z-Wave
################################################

zwave:
  usb_path: !secret zwave_usb_path
  network_key: !secret zwave_network_key
