################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.master_bathroom_sensor:
      <<: *customize
      friendly_name: "Master Bathroom Motion"
      device_class: motion

    ################################################
    ## Input Select
    ################################################


    ################################################
    ## Lock
    ################################################


    ################################################
    ## Thermostat
    ################################################

    zwave.danfoss_z_thermostat_014g0013:
      <<: *expose
      hidden: false

    climate.danfoss_z_thermostat_014g0013_heating_1_2:
      <<: *expose
      hidden: false


    ################################################
    ## Sensor
    ################################################

    sensor.fibaro_system_fgwpef_wall_plug_power_4:
      <<: *expose
      hidden: true

    sensor.fibaro_system_fgwpef_wall_plug_exporting_2:
      <<: *expose
      hidden: true

    sensor.fibaro_system_fgwpef_wall_plug_power_3:
      <<: *expose
      hidden: true

  ################################################
  ## Customize Domain
  ################################################

  customize_domain:
    zwave:
      <<: *customize
      # hidden: true

################################################
## Z-Wave
################################################

zwave:
  usb_path: !secret zwave_usb_path
  network_key: !secret zwave_network_key
