################################################################
## Packages / Z-Wave
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zwave'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Lock
    ################################################

    ################################################
    ## Thermostat
    ################################################

    zwave.danfoss_z_thermostat_014g0013:
      <<: *expose
      hidden: false

    climate.danfoss_z_thermostat_014g0013_heating_1_2:
      <<: *expose
      hidden: false

    ################################################
    ## Sensor
    ################################################

  ################################################
  ## Customize Domain
  ################################################

  customize_domain:
    zwave:
      <<: *customize


################################################
## Z-Wave
################################################

zwave:
  usb_path: !secret zwave_usb_path
  network_key: !secret zwave_network_key

group:
  zwave_hidden:
    name: "Hidden Z-wave"
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level
      - sensor.fibaro_system_fgd212_dimmer_2_exporting
      - sensor.fibaro_system_fgd212_dimmer_2_heat
      - sensor.fibaro_system_fgd212_dimmer_2_power
      - sensor.fibaro_system_fgd212_dimmer_2_power_2
      - sensor.fibaro_system_fgd212_dimmer_2_power_management
      - sensor.fibaro_system_fgd212_dimmer_2_system
      - sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid
      - sensor.fibaro_system_fgd212_dimmer_2_alarm_level
      - sensor.fibaro_system_fgd212_dimmer_2_alarm_type
      - sensor.fibaro_system_fgd212_dimmer_2_exporting
      - sensor.fibaro_system_fgd212_dimmer_2_heat
      - sensor.fibaro_system_fgd212_dimmer_2_power_management
      - sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid
      - sensor.fibaro_system_fgwpef_wall_plug_power
      - sensor.fibaro_system_fgwpef_wall_plug_power_4
      - sensor.fibaro_system_fgwpef_wall_plug_power_3
      - sensor.fibaro_system_fgwpef_wall_plug_exporting_2
      - sensor.fibaro_system_fgms001_motion_sensor_temperature
      - sensor.fibaro_system_fgms001_motion_sensor_general
      - sensor.fibaro_system_fgms001_motion_sensor_luminance
